#!/usr/bin/env python3
"""Generate a small HTML handoff for manually creating upstream PRs."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
from typing import Any


def render_item(item: dict[str, Any]) -> str:
    fields = [
        ("Issue", item.get("issue", "")),
        ("Decision", item.get("decision", "")),
        ("Branch", item.get("branch", "")),
        ("PR title", item.get("pr_title", "")),
        ("Root cause", item.get("root_cause", "")),
    ]
    rows = "\n".join(
        f"<tr><th>{html.escape(label)}</th><td>{html.escape(str(value))}</td></tr>"
        for label, value in fields
        if value
    )
    changes = "".join(f"<li>{html.escape(str(x))}</li>" for x in item.get("changes", []))
    tests = "".join(f"<li>{html.escape(str(x))}</li>" for x in item.get("tests", []))
    blockers = "".join(
        f"<li>{html.escape(str(x))}</li>" for x in item.get("blockers", [])
    )
    body = html.escape(str(item.get("pr_body", "")))
    return f"""
<section>
  <table>{rows}</table>
  <h3>Changed Files</h3><ul>{changes}</ul>
  <h3>Validation</h3><ul>{tests}</ul>
  <h3>Blockers</h3><ul>{blockers}</ul>
  <h3>PR Body</h3><pre>{body}</pre>
</section>
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    data = json.loads(args.input.read_text(encoding="utf-8-sig"))
    items = data.get("items", [])
    rendered_items = "\n".join(render_item(item) for item in items)
    repo = html.escape(str(data.get("repo", "")))
    generated_by = html.escape(str(data.get("generated_by", "github-issue-fix")))
    document = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>PR Handoff</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; line-height: 1.5; }}
    section {{ border: 1px solid #ddd; border-radius: 8px; padding: 1rem; margin: 1rem 0; }}
    th {{ text-align: left; padding-right: 1rem; vertical-align: top; }}
    pre {{ white-space: pre-wrap; background: #f6f8fa; padding: 1rem; border-radius: 6px; }}
  </style>
</head>
<body>
  <h1>PR Handoff</h1>
  <p><strong>Repository:</strong> {repo}</p>
  <p><strong>Generated by:</strong> {generated_by}</p>
  {rendered_items}
</body>
</html>
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(document, encoding="utf-8")


if __name__ == "__main__":
    main()
